version: '3'
services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=yryskeldi
      - POSTGRES_PASSWORD=yryskeldi
      - POSTGRES_DB=hr_backend
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  postgres_data: